import { AuthProvider } from "@/context/AuthContext";
import { Roboto } from 'next/font/google';
import "./globals.css";

const roboto = Roboto({
  subsets: ['latin'],        // Specify the character subsets to load
  weight: ['400', '500', '700'], // Choose the font weights you need
  display: 'swap',           // Use 'swap' for better performance
  variable: '--font-roboto', // Define a CSS variable for the font
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.variable}>
      <body className="h-screen overflow-hidden">
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
